# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint for user mapping

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SaveMappingQueue

Resources:
    SaveMappingQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-mapping-queue
            VisibilityTimeout: 601
    StartSaveMappingFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-mapping.default
            Runtime: nodejs12.x
            Timeout: 3
            MemorySize: 128
            CodeUri: ./dist/start-save-mapping
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-mapping
            Events:
                SaveMappingResource:
                    Type: Api
                    Properties:
                        Path: /save/{proxy+}
                        Method: any
    ProcessSaveMappingFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-mapping.default
            Runtime: nodejs12.x
            CodeUri: ./dist/process-save-mapping
            MemorySize: 128
            ReservedConcurrentExecutions: 1
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-mapping
            Timeout: 60
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SaveMappingQueue.Arn
                        # BatchSize: 1

Outputs:
    SaveUserMappingApi:
        Description: URL to save mapping
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/usermapping'
        Export:
            Name: SaveMappingApi
