# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint for user mapping

Globals:
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SaveMappingQueue

Resources:
    SaveMappingQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-mapping-queue
            VisibilityTimeout: 601
    StartSaveMappingFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-mapping.default
            Runtime: nodejs18.x
            CodeUri: ./dist/start-save-mapping
            Timeout: 3
            MemorySize: 128
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-mapping-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    ProcessSaveMappingFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-mapping.default
            Runtime: nodejs18.x
            CodeUri: ./dist/process-save-mapping
            MemorySize: 128
            ReservedConcurrentExecutions: 1
            VpcConfig:
                SecurityGroupIds:
                    - sg-eccd2691
                SubnetIds:
                    - subnet-894624ec # Only the private subnet
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # For VPC
                - AWSLambdaENIManagementAccess
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-mapping
            Timeout: 60
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SaveMappingQueue.Arn
                        BatchSize: 60
                        MaximumBatchingWindowInSeconds: 60
